name: smartcontracts
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.0.0
  test: ^1.21.0
  web3dart_builders: ^3.0.1
dependencies:
  web3dart: ^3.0.1
